# example values
indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://tgt.by
      name: tgt.by

# user properties
user-properties:
  nameUserAgent: indexBot
  referUserSite: https://github.com/sergeyprokhorovich/SiteSearchEngine
  pageLimit: 5
# conf server
server:
 port: 8080
# conf db in spring
spring:
  datasource:
    username: myuser
    password: mypass
    url: jdbc:postgresql://localhost:5432/search_engine?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
